### ISSUE TITLE
这个节点与Custom_Nodes_AlekPet的节点冲突吗？

### ISSUE THREAD

**Issue by fs920105** [zhuanqianfish/ComfyUI-EasyNode#3]
不知道什么原因安装了你这个节点后，Custom_Nodes_AlekPe的翻译节点就失去了作用，我排查了调整了两个多小时发现是你这个节点造成的，并且删除节点后，Custom_Nodes_AlekPe翻译还是坏的，最后重装了ComfyUI后，翻译才得到修复。

**Comment by zhuanqianfish** [comment]
你好，我的这个节点有部分代码就是参考Custom_Nodes_AlekPe写的，最开始我怀疑是部分代码冲突了，可是我测试了一下并没有发现你说的问题。
而且我也经常使用 “Argos Translate CLIP Text Encode Node 来翻译”图上附上我的测试结果。
![微信截图_20231213165225](https://github.com/zhuanqianfish/ComfyUI-EasyNode/assets/2833412/13d89801-6d19-409b-bc3b-69d91fe3d311)

**Comment by zhuanqianfish** [comment]
我找到了一个可能会导致错误的问题，已经修复了，更新到最新版就行

**Comment by fs920105** [comment]
> 我找到了一个可能会导致错误的问题，已经修复了，更新到最新版就行

我试一下，

**Comment by fs920105** [comment]
> 我找到了一个可能会导致错误的问题，已经修复了，更新到最新版就行

我又测试了新版，还是一样的问题，不过对于绿蛇节点的预览没影响。
第一图是加了你的节点时
![加了节点时](https://github.com/zhuanqianfish/ComfyUI-EasyNode/assets/135109872/6b841050-bbf6-42f1-8a0b-4551a478cba4)
第二图是没加你的节点时
![没加节点时](https://github.com/zhuanqianfish/ComfyUI-EasyNode/assets/135109872/88055e30-b1f9-416b-9465-15e1c90395d4)
第三图是删除节点后问题依然存在
![删除节点后依然恢复不了](https://github.com/zhuanqianfish/ComfyUI-EasyNode/assets/135109872/ad7d44f5-3454-43f7-a764-729c60c09045)
好在绿蛇的预览没影响

**Comment by fs920105** [comment]
图的顺序乱了，不过你应该理解我想表达的

**Comment by fs920105** [comment]
对于整体来说问题不大，可以正常出图，只是我经常加添加调整风格节点，需要观察风格节点输出的内容，所以会用到预览
![只是对于预览有影响](https://github.com/zhuanqianfish/ComfyUI-EasyNode/assets/135109872/1500603e-ec09-4a50-b0b8-d2cac5816521)
