### ISSUE TITLE
This node makes this tab in firefox laggy

### ISSUE THREAD

**Issue by ifloppy** [zhuanqianfish/ComfyUI-EasyNode#4]
正在使用Firefox浏览器。在使用这个节点并开启共享屏幕、在节点中展示画面后，网页非常卡顿。

**Comment by zhuanqianfish** [comment]
你好，我测试中没有发现这个问题，cpu，gpu占用都正常。也没有出现特别卡顿的现象。
目前我认为最大的可能性是代码中使用了setInteval来循环渲染canvas内容，而firefox对这个方法支持或许有一定问题。未来我再进一步研究这个问题。
