### ISSUE TITLE
Super slow wen capturing

### ISSUE THREAD

**Issue by kakachiex2** [zhuanqianfish/ComfyUI-EasyNode#6]
I can't paint it get super slow wen Sharing Im using MyPaint app
![Screenshot 2024-01-01 003149](https://github.com/zhuanqianfish/ComfyUI-EasyNode/assets/1762112/78f99e17-aa50-4a6b-b775-4657e29dc574)

**Comment by zhuanqianfish** [comment]
I have looked at your node diagram and it seems that you made a mistake. The text you entered was intended for external program calls, not for image nodes. In general, only the output Image node needs to be connected in the workflow. You can refer to my workflow  in  the "[ComfyUIPath]\custom_nodes\ComfyUI-EasyNode\Example Workflow"
![123](https://github.com/zhuanqianfish/ComfyUI-EasyNode/assets/2833412/314e92f8-d5f9-41fd-ad44-ccfadc4af46a)
